### ISSUE TITLE
Create authentication page in wiki

### ISSUE THREAD

**Issue by shreytailor** [SE701-T1/frontend#115]
**Describe the task that needs to be done.**

A new page has to be created called _Authentication Flow_ in the wiki. This page should contain information about how Google's OAuth is being used so that users can sign into the application. It should also contain signatures of those endpoints managed by the Users team, namely `/api/users/login` and `/api/validate`.

**Describe how a solution to your proposed task might look like (and any alternatives considered).**

N/A

**Notes**

* This issue was agreed upon by the team as this documentation will help the next team understand our implementation.

**Comment by uoa-ypec413** [comment]
LGTM

**Comment by shreytailor** [comment]
This page has been [created](https://github.com/SE701-T1/frontend/wiki/Authentication-Flow)!
