### ISSUE TITLE
Create issue labels page in wiki

### ISSUE THREAD

**Issue by shreytailor** [SE701-T1/frontend#120]
**Describe the task that needs to be done.**

A page needs to be created in the wiki called _Issue Labels_. This page will contain information about how custom labelling is used in our workflow so that the next team can use the labels in the same way.

**Describe how a solution to your proposed task might look like (and any alternatives considered).**

N/A

**Notes**

- This issue was approved by everyone in the full team meeting on 20th March.

**Comment by uoa-ypec413** [comment]
LGTM!

**Comment by KirstyGong** [comment]
LGTM

**Comment by arathibiju** [comment]
LGTM

**Comment by shreytailor** [comment]
This page has been [created](https://github.com/SE701-T1/frontend/wiki/Issue-Labels)!
