### ISSUE TITLE
Fix tests in Settings page

### ISSUE THREAD

**Issue by shreytailor** [SE701-T1/frontend#125]
**Describe the task that needs to be done.**

The #85 PR had been open for several days because the original assignee couldn't work on the development in the weekend. The CI pipeline was introduced after these changes were made, so we have accidentally introduced some test errors through the merge that need to be fixed immediately.

To reproduce this error, run the `npm run test` command in the project.

<img width="988" alt="image" src="https://user-images.githubusercontent.com/39754888/159144420-9f0b248d-c92c-401d-b364-e88f5a1ea222.png">

**Describe how a solution to your proposed task might look like (and any alternatives considered).**

Look at the failing test and change it so that it passes.

**Notes**

* This issue was created as a high priority because all tests on the `main` branch should be passing.

**Comment by arathibiju** [comment]
LGTM, thank you for picking this up
