### ISSUE TITLE
Refactor and Fix up glitches picked up from Demo 

### ISSUE THREAD

**Issue by scorpionknifes** [SE701-T1/frontend#131]
**Describe the task that needs to be done.**
After doing some demo testing, some changes need to be done in order to make the demo more smooth
- Fix search focus is lost after useState
- Implement similar courses on chat detail page
- Minor UI fixes for flow

**Describe how a solution to your proposed task might look like (and any alternatives considered).**

Fix final details

**Notes**

**Comment by ff-dev-45** [comment]
SGTM, lets get this done!
