### ISSUE TITLE
React route middleware

### ISSUE THREAD

**Issue by shreytailor** [SE701-T1/frontend#16]
**Describe the task that needs to be done.**

There needs to be a React Router authentication middleware implemented, which can be used across the different pages of the application to check if the user is currently logged in.

**Describe how a solution to your proposed task might look like (and any alternatives considered).**

A solution is to create a class that extends `Route` from `react-router` and is called `AuthenticatedRoute`. Any page which needs the user to be authenticated should use this component, as it performs the pre-check.

```js
// Note: This is just pseudocode.

class AuthenticatedRoute extends Route {
  render() {

    /*
    This check can be performed in two ways. Either store our custom JWT in the local-storage
    of the browser or in React context. Thereafter, just check if it exists.
    */
    if (!authenticated) {
      // Return a redirect to login route.
    }

    // Return a redirect to the desired component.
  }
}
```

**Notes**

- This was discussed in the Users team meeting on the 14th March, and also in the front-end meeting on the 10th March.
- The high-level detail of this approach was agreed upon by everyone.
- The due date for this issue is 16th March night.
- ~~Blocked by #16~~

**Comment by dshah1901** [comment]
LGTM!
