### ISSUE TITLE
Scaffold Upload Page

### ISSUE THREAD

**Issue by jessicafenwick** [SE701-T1/frontend#17]
**Describe the task that needs to be done.**
Create basic page for uploading timetable. Does not need functionality or styling. 

**Describe how a solution to your proposed task might look like (and any alternatives considered).**
Basic skeleton of an upload page similar to designs on figma

**Notes**
This issue was discussed during a team meeting at 11/03/22 and approved by the timetable team then

**Comment by arathibiju** [comment]
During a timetable team meeting on 14/03/2022 it was decided for a better UX that a submit button needs to be added for the URL text field.

**Comment by arathibiju** [comment]
Closed by #49
