### ISSUE TITLE
Implement frontend of file upload

### ISSUE THREAD

**Issue by jessicafenwick** [SE701-T1/frontend#18]
**Describe the task that needs to be done.**
Investigate how to upload an .ics file on the frontend. Ways to store the file needs to be considered as well. The relevant component is called UploadPage and is located in the pages folder in the react app

**Describe how a solution to your proposed task might look like (and any alternatives considered).**
Can upload .ics file on upload page using the existing upload timetable button using method determined by investigation

**Notes**
This issue was discussed and approved during a timetable team meeting on 11/03/22.

**Comment by ff-dev-45** [comment]
discussed in team meeting 3/20/22, left as future work

**Comment by jessicafenwick** [comment]
File Upload with React [https://www.pluralsight.com/guides/uploading-files-with-reactjs](url)
