### ISSUE TITLE
Scaffold Courses Page

### ISSUE THREAD

**Issue by jessicafenwick** [SE701-T1/frontend#19]
**Describe the task that needs to be done.**
Create basic page for displaying courses. Does not need functionality or styling.

**Describe how a solution to your proposed task might look like (and any alternatives considered).**
Basic skeleton of an course display page similar to designs on figma

**Notes** 
This issue was discussed and approved during a timetable team meeting on 11/03/22.

**Comment by arathibiju** [comment]
closed by #91
