### ISSUE TITLE
Add Code Owners

### ISSUE THREAD

**Issue by uoa-ypec413** [SE701-T1/frontend#23]
**Describe the task that needs to be done.**
Code owners need to be added so that the right people are automatically requested for review when PRs are made in directories relevant to them.

**Describe how a solution to your proposed task might look like (and any alternatives considered).**
Split the `src` directory into folders by features . The frontend devs in each team will be code owners for their feature subdirectory.

I see that we have already set up `components` and `pages` subdirectories, so I need some advice on how to best incorporate the feature subdirectories. 
Option 1:
![image](https://user-images.githubusercontent.com/68877945/157973856-70972e29-9d9f-42ea-8dfa-33f174e1605b.png)

Option 2:
![image](https://user-images.githubusercontent.com/68877945/157973835-fa9f28c5-3a1b-405f-a625-e9b619268677.png)

**Notes**
Could I get some advice from the frontend team as to how to go about this, since I'm in backend and don't know about the plans for the frontend repo.

**Comment by ff-dev-45** [comment]
discussed in team meeting 3/20/22, decided not to be done for the frontend,
