### ISSUE TITLE
Carousel component for the Splash Page.

### ISSUE THREAD

**Issue by dshah1901** [SE701-T1/frontend#28]
**Describe the task that needs to be done.**

Create a carousel with three slides where we introduce the application to the user.

**Describe what a solution to your proposed task might look like (and any alternatives considered).**

The carousel component should be relatively reusable and should not contain any hard-coded values within it. The carousel should accept a prop called `data` which will have the format below. It describes what information should be should in the carousel.

```js
[{
  title: "Introducing BuddyMakers",
  description: "An innovative way to meet new students who take the same course as you."
}]
```

Each object in this array describes one page. The carousel should hence be able to display as many pages as needed, depending on this prop.

This is what the end product of the UI should look like ([source](https://www.figma.com/file/s4xJvh3Q3mvYEKGAULzwbh/Class-Buddy-Match?node-id=0%3A1)).

<img width="932" alt="image" src="https://user-images.githubusercontent.com/39754888/157998532-6d33ccdd-7554-48bc-be06-e32231f4c539.png">

**Notes**

- This task was approved by the Users team in the meeting held on 12/03.

**Comment by DanilLinkov** [comment]
LGMT
