### ISSUE TITLE
Sign In

### ISSUE THREAD

**Issue by dshah1901** [SE701-T1/frontend#30]
**Describe the task that needs to be done.**
The UI of the sign-in button. When clicked the button authenticates the user and authorizes the user to access different components of the application application

**Describe what a solution to your proposed task might look like (and any alternatives considered).**
Using OAuth for authentication, and using the `react-google-login` package which provides simple mechanisms to add the Google login.

**Notes**
N/A

**Comment by DanilLinkov** [comment]
LGMT
