### ISSUE TITLE
Link URL input on upload page

### ISSUE THREAD

**Issue by jessicafenwick** [SE701-T1/frontend#47]
**Describe the task that needs to be done.**
Link the URL input on the frontend to API endpoint defined in backend issue #52 on click of submit button

**Describe how a solution to your proposed task might look like (and any alternatives considered).**
When submit button is clicked, endpoint to upload file via URL is called.

**Notes**
Currently no submit button, as of 14/03 meeting. Adding to #17, this is dependent on #17 
Edit: as of 14/03/22 Submit button has been added to the upload page component

**Comment by arathibiju** [comment]
This issue has been partially implemented but is blocked by issue 51 on the back-end repo. Once the end point has been defined this issue can be completed as it requires knowledge of how the endpoint is set up
