### ISSUE TITLE
Link file upload on upload page

### ISSUE THREAD

**Issue by jessicafenwick** [SE701-T1/frontend#48]
**Describe the task that needs to be done.**
Link the file input on the front-end to API endpoint defined in back-end issue #52 on click of submit button

**Describe how a solution to your proposed task might look like (and any alternatives considered).**
When submit button is clicked, endpoint to upload file via URL is called and the file is successfully uploaded.

**Notes** 
The relevant component for this issue is the UploadPage component which is located in the Pages folder in the react app
Blocked by #52 Back-end

**Comment by ff-dev-45** [comment]
discussed in team meeting 3/20/22, left for next team
