### ISSUE TITLE
BUG: Warnings in timetable upload page tests

### ISSUE THREAD

**Issue by arathibiju** [SE701-T1/frontend#55]
**Describe the task that needs to be done.**
Bug Report: Some tests in the timetable upload page are generating warnings due to a required prop not being passed in to the component.
![image](https://user-images.githubusercontent.com/62319771/158267154-cdd2b6e8-8a52-4b57-a88b-46f1c335dcb0.png)

**Describe how a solution to your proposed task might look like (and any alternatives considered).**
Add in the required prop, a function, to the UploadPage component. Issue can be considered closed when this warning no longer appears

**Notes**
This warning was discovered by @shreytailor and reported on the group discord server.

**Comment by shreytailor** [comment]
LGTM! Thanks for creating this ticket
