### ISSUE TITLE
BUG: Fix Course Card Component card bug

### ISSUE THREAD

**Issue by KirstyGong** [SE701-T1/frontend#56]
**Describe the task that needs to be done.**
*(If this issue is about a bug, please describe the problem and steps to reproduce the issue. You can also include screenshots of any stack traces, or any other supporting images).*
The Course Card Component tests are not passing due to the change of structure. The test can be reproduce by running npm test
**Describe how a solution to your proposed task might look like (and any alternatives considered).**
Rewrite the test
**Notes**

**Comment by shreytailor** [comment]
LGTM! Thanks for creating this ticket
