### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by dshah1901** [SE701-T1/frontend#64]
**Describe the task that needs to be done.**
Putting together a Login page component that includes the button and the carousel component created earlier. Also using media queries to make it responsive( adjusts to various devices eg. tablets, desktop, mobile.)

**Describe what a solution to your proposed task might look like (and any alternatives considered).**
Make a Login page in `src/pages/Login` and assemble both components there. This is what the UI is supposed to look like:

<p align="center">
  <img width="600" alt="image" src="https://user-images.githubusercontent.com/73872595/158304441-d80345ed-9aec-42aa-8a00-3882fbe9f36e.png">
</p>

**Notes**
N/A

**Comment by DanilLinkov** [comment]
LGMT

**Comment by shreytailor** [comment]
LGTM!
