### ISSUE TITLE
Automate request authorization header

### ISSUE THREAD

**Issue by shreytailor** [SE701-T1/frontend#68]
**Describe the task that needs to be done.**

In the frontend of the application, the JWT token is accessible anywhere in the application, through the React context implemented in Issue #54 . However, it would be tedious for the frontend developers to manually access this JWT each time they want to make a backend request, and attach it to the Authorization header of the request.

Hence, we need to find a way to automate this task such that there is no code duplication and it's easy for everyone to work.

**Describe how a solution to your proposed task might look like (and any alternatives considered).**

*Approach One*

Using the `axios` library to make requests gives us the ability to use interceptors (middleware that attach the Authorization header to all outgoing requests from the frontend). This would mean that after defining the interceptor, no extra work would be needed.

**Notes**

- The frontend team is happy using `axios` based on the whole group meeting held on 15th March.
- I suggested that we should automate this process so that the frontend team should not have to worry about attaching the headers manually, and the whole process would become a lot easier.

**Comment by scorpionknifes** [comment]
LGTM
