### ISSUE TITLE
BUG: Warnings in dialogues list test

### ISSUE THREAD

**Issue by sv-singh** [SE701-T1/frontend#78]
**Describe the task that needs to be done.**
Bug Report: Some tests in the dialogues list component are showing warnings due to unexpected prop types

**Describe how a solution to your proposed task might look like (and any alternatives considered).**
Change the currentUser prop type in dialogues list test to number (currently string), as a number is the expected prop type

**Notes**
N/A

**Comment by DanilLinkov** [comment]
LGTM
