### ISSUE TITLE
Settings Page (Button to toggle pairing)

### ISSUE THREAD

**Issue by dshah1901** [SE701-T1/frontend#83]
**Describe the task that needs to be done.**
Work on the UI of the setting page, which will consist of a single toggle button for user pairing enabled.

**Describe what a solution to your proposed task might look like (and any alternatives considered).**
Using the toggle button component in MUI. 

**Notes**
NA

**Comment by ff-dev-45** [comment]
discussed in team meeting 3/20/22, will be followed up with by User team
