### ISSUE TITLE
Log out button

### ISSUE THREAD

**Issue by dshah1901** [SE701-T1/frontend#84]
**Describe the task that needs to be done.**

This issue was discussed in the team meeting of the user's team on 17th of March 2022 and all team members approved this issue.
There should be a way for users to log out from the application. A possible place to put the 'Log Out' button would be the `Settings` page component or the `SideBar` component.

**Describe what a solution to your proposed task might look like (and any alternatives considered).**

Logging out the user from the client-side would consist of accessing the `AuthContext` and clearing the JWT token from the global context. This would automatically take the user to the `/login` page because they cannot access the protected routes anymore. 

**Notes**

- This issue will be worked on by the next team.

**Comment by ff-dev-45** [comment]
discussed in team meeting 3/20/22, left as a future issue
