### ISSUE TITLE
Integrate pairing popup to pairing page

### ISSUE THREAD

**Issue by KirstyGong** [SE701-T1/frontend#94]
**Describe the task that needs to be done.**
After the user clicks on the "FIND MY BUDDY" button, the pairing dialog will show up to shows the pairing result.

**Describe how a solution to your proposed task might look like (and any alternatives considered).**
The "FIND MY BUDDY" button will have a function call to show the pop up and it will also pass a list of selected courses  (eg:["Softeng701", "Softeng754"]) . Then pairing pop up can use the list to search for a buddy. 

**Notes**
Block by #12

**Comment by DanilLinkov** [comment]
LGTM

**Comment by KirstyGong** [comment]
Completed by CZ
