### ISSUE TITLE
Documentation: Remove place holders in contributing guidelines

### ISSUE THREAD

**Issue by arathibiju** [SE701-T1/frontend#98]
**Describe the task that needs to be done.**
The contributing guidelines currently has placeholder data from the start of the project. These need to be populated with current information

**Describe how a solution to your proposed task might look like (and any alternatives considered).**
Complete contributing guidelines

**Notes**

**Comment by jessicafenwick** [comment]
lgtm

**Comment by shreyasingaraju** [comment]
LGTM!

**Comment by arathibiju** [comment]
Closed by #100
